<a href="https://colab.research.google.com/github/Revendra-deshmukh/imageclassification/blob/main/DS-MINOR-JAN..ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Data : Images 
# 1. Download manually the images from Google
# 2. Download dataset from Kaggle.com
# 3. Build a Image Web Crawler
# 4. Use Python Libraries to scrape the images (Using)

In [ ]:
!pip install ipython-autotime
%load_ext autotime
!pip install bing-image-downloader
!mkdir images 
 

In [ ]:
from bing_image_downloader import downloader 
downloader.download("Sunflower",limit=30,output_dir="images",adult_filter_off=True)
from bing_image_downloader import downloader 
downloader.download("ice cream cone",limit=30,output_dir="images",adult_filter_off=True)
from bing_image_downloader import downloader 
downloader.download("rugby ball leather",limit=30,output_dir="images",adult_filter_off=True)

In [ ]:
import numpy as np
a= np.array([1,2,3,4,5])
b= np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(a.ndim,b.ndim)


In [ ]:
# How do i convert matrix to vector? - flatten()
b.flatten()

In [ ]:
#Preprocessing
# 1. resize
# 2. flatten

import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

target = []
images = []
flat_data = []

DATADIR = '/content/drive/MyDrive'
CATEGORIES = ['sunflower','rugby boll','ice cream cone']
for category in CATEGORIES:
  class_num = CATEGORIES.index(category) # Label Encoding the values
  path = os.path.join(DATADIR,category)
  #print(path)
  for img in os.listdir(path):
    imagerepeat = imread(os.path.join(path,img))
    """print(img_array.shape)
    print(img_array)
    plt.imshow(img_array)"""
    img_resized = resize(img_array,(150,150,3)) # normalizes
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)
flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)



In [ ]:
len(flat_data[0])
150*150*3

67500

In [ ]:
target

In [ ]:
unique,count = np.unique(target,return_counts=True)
plt.bar(CATEGORIES,count)

In [ ]:
# split data into Traning and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,test_size=0.3,random_state=109)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm 
param_grid = [
              {'C':[1,10,100,1000],'kernel':['linear']},
              {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']},
]
svc = svm.SVC(probability=True)
clf = GridSearchCV(svc,param_grid) 
clf.fit(x_train,y_train)

NameError: ignored

In [ ]:
y_pred = clf.predict(x_test)
y_pred

array([0, 0, 2, 2, 0, 2, 0, 2, 2, 0, 0, 2, 1, 1, 2, 2, 1, 2, 0, 2, 2, 2,
       1, 2, 0, 0, 0, 0, 2, 0, 2, 1, 0, 0, 2, 0, 2, 2])

In [ ]:
y_test

array([0, 0, 2, 2, 0, 2, 0, 2, 1, 0, 0, 2, 1, 1, 2, 2, 1, 2, 0, 2, 1, 2,
       1, 2, 2, 0, 0, 0, 1, 0, 2, 1, 0, 0, 2, 0, 1, 2])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
accuracy_score(y_pred,y_test)

0.868421052631579

In [ ]:
confusion_matrix(y_pred,y_test)

array([[14,  0,  1],
       [ 0,  5,  0],
       [ 0,  4, 14]])

In [ ]:
# Save the model using Pickel Library
import pickle
pickle.dump(clf,open('img_model.p','wb'))

NameError: ignored

In [ ]:
model = pickle.load(open('img_model.p','rb'))

FileNotFoundError: ignored

In [ ]:
# Testing a brand new Image
flat_data = []
url = input("enter url")
img = imread(url)
img_resized = resize(img,(150,150,3)) # normalizes
flat_data.append(img_resized.flatten())
flat_data = np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out = model.predict(flat_data)
y_out = CATEGORIES[y_out[0]]
print(f' PREDICTED OUTPUT: {y_out}')

enter urlhttps://www.hellowonderful.co/ckfinder/userfiles/images/10-tissue-paper-flower-ice-cream-cones.jpg


NameError: ignored

In [ ]:
!pip install streamlit

     |████████████████████████████████| 7.5MB 3.8MB/s 
     |████████████████████████████████| 163kB 47.8MB/s 
     |████████████████████████████████| 4.6MB 54.0MB/s 
     |████████████████████████████████| 81kB 7.7MB/s 
     |████████████████████████████████| 112kB 37.5MB/s 
     |████████████████████████████████| 71kB 8.0MB/s 
     |████████████████████████████████| 122kB 56.2MB/s 
  Created wheel for blinker: filename=blinker-1.4-cp36-none-any.whl size=13450 sha256=9de1f05b0c32e579a0fc9bceb114ec73dca273af3afc853a237e06a8bce65035
  Stored in directory: /root/.cache/pip/wheels/92/a0/00/8690a57883956a301d91cf4ec999cc0b258b01e3f548f86e89
Successfully built blinker
ERROR: google-colab 1.0.0 has requirement ipykernel~=4.10, but you'll have ipykernel 5.4.3 which is incompatible.
  Found existing installation: ipykernel 4.10.1
    Uninstalling ipykernel-4.10.1:
      Successfully uninstalled ipykernel-4.10.1


In [ ]:
!pip install pyngrok==4.1.1


In [ ]:
from pyngrok import ngrok

In [ ]:
%%writefile app.py
import streamlit as st 
import numpy as np
from skimage.io import imread
from skimage.transform import resize
import pickle
from PIL import Image
st.set_option('deprecation.showfileUploaderEncoding', False)
st.title('Image Classifier using ML')
st.text('Upload image')

model = pickle.load(open('img_model.p','rb'))

uploaded_file = st.file_uploader("choose ", type="jpg")
if uploaded_file is not None:
  img = Image.open(uploaded_file)
  st.image(img,caption='Uploaded Image')
  if st.button('PREDICT'):
    CATEGORIES = ['sunflower','rugby boll','ice cream cone']
    st.write("result")
    flat_data=[]
    img = np.array(img)
    img_resized = resize(img,(150,150,3)) # normalizes
    flat_data.append(img_resized.flatten())
    flat_data = np.array(flat_data)
    y_out = model.predict(flat_data)
    y_out = CATEGORIES[y_out[0]]
    st.title(f' PREDICTED OUTPUT: {y_out}')
    

Overwriting app.py


In [ ]:
!nohup streamlit run app.py &
url = ngrok.connect(port='8501')
url

nohup: appending output to 'nohup.out'


'http://2ac4d37364ab.ngrok.io'